server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    locations: 'classpath:db/migration'
    baselineOnMigrate: true
    validateOnMigrate: false

  mail:
    host: ${MAIL_HOST}
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: 'smpts'

springdoc:
  swagger-ui:
    path: '/'
  packages-to-scan: com.dreamteam.eduuca.controllers

logging:
  level:
    root: INFO
    com.dreamteam.eduuca: TRACE